# Generated by Django 3.1.5 on 2021-08-20 13:58

from django.db import migrations
import users.formatchecker


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=users.formatchecker.ContentTypeRestrictedFileField(null=True, upload_to='users/uploads/%Y/%m/%d/'),
        ),
    ]
