# Generated by Django 3.1.5 on 2021-09-20 11:18

from django.db import migrations
import users.formatchecker


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210820_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=users.formatchecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='users/uploads/%Y/%m/%d/'),
        ),
    ]
