# Generated by Django 3.1.5 on 2021-09-20 11:25

from django.db import migrations
import users.formatchecker


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210920_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=users.formatchecker.ContentTypeRestrictedFileField(null=True, upload_to='users/uploads/%Y/%m/%d/'),
        ),
    ]
