version: "3.8"

services:

  postgres_db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=test_new_norm
      - POSTGRES_USER=hikki
      - POSTGRES_PASSWORD=adi
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: sh -c "./manage.py makemigrations && ./manage.py migrate && ./manage.py collectstatic
      --no-input && gunicorn -b 0.0.0.0:8000 unnamed_project.wsgi --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db


  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
    depends_on:
      - web
      - postgres_db
    ports:
      - "80:80"
      - "443:443"


volumes:
  postgres_data:
